resilience4j:
  circuitbreaker:
    instances:
      createRating:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.RestClientException
          - java.io.IOException
